services:
  - type: cron
    name: update-fantasy-rosters
    schedule: "0 16 * * *"  # 4:00 PM UTC every day
    env: python
    buildCommand: ""
    startCommand: "python load_teams_from_espn.py"
    autoDeploy: true
