name: Daily Fantasy Snapshot & Ownership Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '50 16 * * *'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ GitHub Actions is working!"
