name: Daily Fantasy Snapshot & Ownership Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '50 16 * * *'  # 12:50 PM ET daily

jobs:
  run-snapshot-and-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install python-dotenv requests

      - name: Run daily snapshot
        run: |
          python load_teams_from_espn.py --save-snapshot

      - name: Run ownership tracker
        run: |
          python ownership_tracker.py

      - name: Commit and push changes (only if files exist)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only add snapshot files that exist
          SNAPSHOTS=$(ls teams_*.json 2>/dev/null || true)
          if [ -n "$SNAPSHOTS" ] || [ -f "ownership_log.json" ]; then
            git add $SNAPSHOTS ownership_log.json
            git commit -m "📸 Auto snapshot + ownership log for $(date +'%Y-%m-%d')" || echo "No changes to commit"
            git push
          else
            echo "⚠️ No snapshot or ownership_log.json found — skipping commit"
          fi
