name: Update GitHub Action Cron from MLB Schedule

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 8:00 AM ET
  workflow_dispatch:

jobs:
  update-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_PUSH }}


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run mlbgame_start.py to update cron
        run: python mlbgame_start.py

      - name: Commit and push updated cron using PAT
        run: |
          git config user.name "cron-updater"
          git config user.email "cron@fantasybot.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_FOR_PUSH }}@github.com/${{ github.repository }}
          git add .github/workflows/daily-roster-sync.yml
          git commit -m "⏰ Auto-update Render cron to match MLB schedule" || echo "No cron changes to commit"
          git push origin HEAD:master


