name: Update GitHub Action Cron from MLB Schedule

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 8:00 AM ET (12:00 UTC)
  workflow_dispatch:

jobs:
  update-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run mlbgame_start.py to update cron
        run: python mlbgame_start.py

      - name: Commit and push updated cron
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/daily-roster-sync.yml
          git commit -m "⏰ Auto-update Render cron to match MLB schedule" || echo "No cron changes to commit"
          git push
